#+TITLE: \textbf{\today:} CPP from BDDs (simple example), updated.
#+OPTIONS: toc:nil author:nil date:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Run a code :noexport:
#+name: UFL_out
#+begin_src bash  :results verbatim :cache yes
python ../../UFL.py
#+end_src

#+RESULTS[2005df20c68b602600e9c39d1bc3acc093c2efcd]: UFL_out
#+begin_example
Using license file /home/bochkarev/gurobi.lic
Academic license - for non-commercial use only
Minimize
   <gurobi.LinExpr: 0.1 A_vh0_1 + 0.2 A_vh9_11 + 0.2 A_vh10_13 + 0.3 A_vh20_22 + 0.3 A_vh21_24 + C_vh0_1 + 2.0 C_vh3_4 + C_vl3_4 + C_vh2_4 + 2.0 C_vh8_10 + C_vl8_10 + 3.0 C_vh9_10 + 2.0 C_vl9_10 + C_vh7_10 + C_vh11_-1 + 2.0 C_vh12_-1 + C_vl12_-1>
Subject To
   A_cont-at-0 : <gurobi.LinExpr: -1.0 A_vh0_1 + -1.0 A_vl0_2> = -1.0
   A_bin-link-1 : <gurobi.LinExpr: link_x1 + -1.0 A_vh0_1> = 0.0
   A_cont-at-1 : <gurobi.LinExpr: A_vh0_1 + -1.0 A_vh1_3 + -1.0 A_vl1_5> = 0.0
   A_cont-at-2 : <gurobi.LinExpr: A_vl0_2 + -1.0 A_vh2_5 + -1.0 A_vl2_4> = 0.0
   A_bin-link-2 : <gurobi.LinExpr: link_z1-1 + -1.0 A_vh1_3 + -1.0 A_vh2_5> = 0.0
   A_cont-at-3 : <gurobi.LinExpr: A_vh1_3 + -1.0 A_vh3_6 + -1.0 A_vl3_8> = 0.0
   A_cont-at-4 : <gurobi.LinExpr: A_vl2_4 + -1.0 A_vh4_8 + -1.0 A_vl4_7> = 0.0
   A_cont-at-5 : <gurobi.LinExpr: A_vl1_5 + A_vh2_5 + -1.0 A_vh5_8 + -1.0 A_vl5_8> = 0.0
   A_bin-link-3 : <gurobi.LinExpr: link_z1-2 + -1.0 A_vh3_6 + -1.0 A_vh4_8 + -1.0 A_vh5_8> = 0.0
   A_cont-at-8 : <gurobi.LinExpr: A_vl3_8 + A_vh4_8 + A_vh5_8 + A_vl5_8 + -1.0 A_vh8_10 + -1.0 A_vl8_10> = 0.0
   A_cont-at-6 : <gurobi.LinExpr: A_vh3_6 + -1.0 A_vh6_9 + -1.0 A_vl6_10> = 0.0
   A_cont-at-7 : <gurobi.LinExpr: A_vl4_7 + -1.0 A_vh7_10 + -1.0 A_vl7_9> = 0.0
   A_bin-link-4 : <gurobi.LinExpr: link_z1-3 + -1.0 A_vh8_10 + -1.0 A_vh6_9 + -1.0 A_vh7_10> = 0.0
   A_cont-at-9 : <gurobi.LinExpr: A_vh6_9 + A_vl7_9 + -1.0 A_vh9_11 + -1.0 A_vl9_12> = 0.0
   A_cont-at-10 : <gurobi.LinExpr: A_vh8_10 + A_vl8_10 + A_vl6_10 + A_vh7_10 + -1.0 A_vh10_13 + -1.0 A_vl10_13> = 0.0
   A_bin-link-5 : <gurobi.LinExpr: link_x2 + -1.0 A_vh9_11 + -1.0 A_vh10_13> = 0.0
   A_cont-at-11 : <gurobi.LinExpr: A_vh9_11 + -1.0 A_vh11_14 + -1.0 A_vl11_16> = 0.0
   A_cont-at-12 : <gurobi.LinExpr: A_vl9_12 + -1.0 A_vh12_16 + -1.0 A_vl12_15> = 0.0
   A_cont-at-13 : <gurobi.LinExpr: A_vh10_13 + A_vl10_13 + -1.0 A_vh13_16 + -1.0 A_vl13_16> = 0.0
   A_bin-link-6 : <gurobi.LinExpr: link_z2-2 + -1.0 A_vh11_14 + -1.0 A_vh12_16 + -1.0 A_vh13_16> = 0.0
   A_cont-at-14 : <gurobi.LinExpr: A_vh11_14 + -1.0 A_vh14_17 + -1.0 A_vl14_19> = 0.0
   A_cont-at-16 : <gurobi.LinExpr: A_vl11_16 + A_vh12_16 + A_vh13_16 + A_vl13_16 + -1.0 A_vh16_19 + -1.0 A_vl16_19> = 0.0
   A_cont-at-15 : <gurobi.LinExpr: A_vl12_15 + -1.0 A_vh15_19 + -1.0 A_vl15_18> = 0.0
   A_bin-link-7 : <gurobi.LinExpr: link_z2-3 + -1.0 A_vh14_17 + -1.0 A_vh16_19 + -1.0 A_vh15_19> = 0.0
   A_cont-at-17 : <gurobi.LinExpr: A_vh14_17 + -1.0 A_vh17_20 + -1.0 A_vl17_21> = 0.0
   A_cont-at-18 : <gurobi.LinExpr: A_vl15_18 + -1.0 A_vh18_21 + -1.0 A_vl18_20> = 0.0
   A_cont-at-19 : <gurobi.LinExpr: A_vl14_19 + A_vh16_19 + A_vl16_19 + A_vh15_19 + -1.0 A_vh19_21 + -1.0 A_vl19_21> = 0.0
   A_bin-link-8 : <gurobi.LinExpr: link_z2-4 + -1.0 A_vh17_20 + -1.0 A_vh18_21 + -1.0 A_vh19_21> = 0.0
   A_cont-at-20 : <gurobi.LinExpr: A_vh17_20 + A_vl18_20 + -1.0 A_vh20_22 + -1.0 A_vl20_23> = 0.0
   A_cont-at-21 : <gurobi.LinExpr: A_vl17_21 + A_vh18_21 + A_vh19_21 + A_vl19_21 + -1.0 A_vh21_24 + -1.0 A_vl21_24> = 0.0
   A_bin-link-9 : <gurobi.LinExpr: link_x3 + -1.0 A_vh20_22 + -1.0 A_vh21_24> = 0.0
   A_cont-at-24 : <gurobi.LinExpr: A_vh21_24 + A_vl21_24 + -1.0 A_vh24_27 + -1.0 A_vl24_27> = 0.0
   A_cont-at-23 : <gurobi.LinExpr: A_vl20_23 + -1.0 A_vh23_27 + -1.0 A_vl23_26> = 0.0
   A_cont-at-22 : <gurobi.LinExpr: A_vh20_22 + -1.0 A_vh22_25 + -1.0 A_vl22_27> = 0.0
   A_bin-link-10 : <gurobi.LinExpr: link_z3-3 + -1.0 A_vh24_27 + -1.0 A_vh23_27 + -1.0 A_vh22_25> = 0.0
   A_cont-at-25 : <gurobi.LinExpr: A_vh22_25 + -1.0 A_vh25_-1 + -1.0 A_vl25_-2> = 0.0
   A_cont-at-26 : <gurobi.LinExpr: A_vl23_26 + -1.0 A_vh26_-2 + -1.0 A_vl26_-1> = 0.0
   A_cont-at-27 : <gurobi.LinExpr: A_vh24_27 + A_vl24_27 + A_vh23_27 + A_vl22_27 + -1.0 A_vh27_-2 + -1.0 A_vl27_-2> = 0.0
   A_bin-link-11 : <gurobi.LinExpr: link_z3-4 + -1.0 A_vh25_-1 + -1.0 A_vh26_-2 + -1.0 A_vh27_-2> = 0.0
   A_cont-at--1 : <gurobi.LinExpr: A_vh25_-1 + A_vl26_-1> = 1.0
   A_cont-at--2 : <gurobi.LinExpr: A_vl25_-2 + A_vh26_-2 + A_vh27_-2 + A_vl27_-2> = 0.0
   C_cont-at-0 : <gurobi.LinExpr: -1.0 C_vh0_1 + -1.0 C_vl0_1> = -1.0
   C_bin-link-1 : <gurobi.LinExpr: link_z1-1 + -1.0 C_vh0_1> = 0.0
   C_cont-at-1 : <gurobi.LinExpr: C_vh0_1 + C_vl0_1 + -1.0 C_vh1_3 + -1.0 C_vl1_2> = 0.0
   C_bin-link-2 : <gurobi.LinExpr: link_z1-2 + -1.0 C_vh1_3> = 0.0
   C_cont-at-3 : <gurobi.LinExpr: C_vh1_3 + -1.0 C_vh3_4 + -1.0 C_vl3_4> = 0.0
   C_cont-at-2 : <gurobi.LinExpr: C_vl1_2 + -1.0 C_vh2_4 + -1.0 C_vl2_4> = 0.0
   C_bin-link-3 : <gurobi.LinExpr: link_z2-2 + -1.0 C_vh3_4 + -1.0 C_vh2_4> = 0.0
   C_cont-at-4 : <gurobi.LinExpr: C_vh3_4 + C_vl3_4 + C_vh2_4 + C_vl2_4 + -1.0 C_vh4_6 + -1.0 C_vl4_5> = 0.0
   C_bin-link-4 : <gurobi.LinExpr: link_z1-3 + -1.0 C_vh4_6> = 0.0
   C_cont-at-6 : <gurobi.LinExpr: C_vh4_6 + -1.0 C_vh6_9 + -1.0 C_vl6_8> = 0.0
   C_cont-at-5 : <gurobi.LinExpr: C_vl4_5 + -1.0 C_vh5_8 + -1.0 C_vl5_7> = 0.0
   C_bin-link-5 : <gurobi.LinExpr: link_z2-3 + -1.0 C_vh6_9 + -1.0 C_vh5_8> = 0.0
   C_cont-at-8 : <gurobi.LinExpr: C_vl6_8 + C_vh5_8 + -1.0 C_vh8_10 + -1.0 C_vl8_10> = 0.0
   C_cont-at-9 : <gurobi.LinExpr: C_vh6_9 + -1.0 C_vh9_10 + -1.0 C_vl9_10> = 0.0
   C_cont-at-7 : <gurobi.LinExpr: C_vl5_7 + -1.0 C_vh7_10 + -1.0 C_vl7_10> = 0.0
   C_bin-link-6 : <gurobi.LinExpr: link_z3-3 + -1.0 C_vh8_10 + -1.0 C_vh9_10 + -1.0 C_vh7_10> = 0.0
   C_cont-at-10 : <gurobi.LinExpr: C_vh8_10 + C_vl8_10 + C_vh9_10 + C_vl9_10 + C_vh7_10 + C_vl7_10 + -1.0 C_vh10_12 + -1.0 C_vl10_11> = 0.0
   C_bin-link-7 : <gurobi.LinExpr: link_z2-4 + -1.0 C_vh10_12> = 0.0
   C_cont-at-11 : <gurobi.LinExpr: C_vl10_11 + -1.0 C_vh11_-1 + -1.0 C_vl11_-1> = 0.0
   C_cont-at-12 : <gurobi.LinExpr: C_vh10_12 + -1.0 C_vh12_-1 + -1.0 C_vl12_-1> = 0.0
   C_bin-link-8 : <gurobi.LinExpr: link_z3-4 + -1.0 C_vh11_-1 + -1.0 C_vh12_-1> = 0.0
   C_cont-at--1 : <gurobi.LinExpr: C_vh11_-1 + C_vl11_-1 + C_vh12_-1 + C_vl12_-1> = 1.0
   C_cont-at--2 : <gurobi.LinExpr: 0.0> = 0.0
Binaries
   ['link_x1', 'link_z1-1', 'link_z1-2', 'link_z1-3', 'link_x2', 'link_z2-2', 'link_z2-3', 'link_z2-4', 'link_x3', 'link_z3-3', 'link_z3-4']
#+end_example

* Parse results into latex                                         :noexport:
#+begin_src bash :stdin UFL_out :results verbatim
cat | tail -n+3 | sed 's/<gurobi\.LinExpr\: //' | sed 's/> =/ =/' | \
    sed 's/: /\& $/g' | \
    sed 's/^[ ]*\([AC]\)_/    \1: /g' | \
    sed 's/_-1/_T/g' | \
    sed 's/_-2/_F/g' | \
    sed 's/--1/-T/g' | \
    sed 's/--2/-F/g' | \
    sed 's/\([AC]\)_v\([hl]\)\([0-9\-]*\)_\([TF0-9\-]*\)/v^\1_{\3 \\rightarrow \4, \2}/g' | \
    sed 's/+ -/-/g' | \
    sed 's/link_\([0-9xz-]*\)/\\lambda_{\1}/g' | \
    sed 's/$/\$\\\\/g'
#+end_src

#+RESULTS:
#+begin_example
Minimize$\\
   0.1 v^A_{0 \rightarrow 1, h} + 0.2 v^A_{9 \rightarrow 11, h} + 0.2 v^A_{10 \rightarrow 13, h} + 0.3 v^A_{20 \rightarrow 22, h} + 0.3 v^A_{21 \rightarrow 24, h} + v^C_{0 \rightarrow 1, h} + 2.0 v^C_{3 \rightarrow 4, h} + v^C_{3 \rightarrow 4, l} + v^C_{2 \rightarrow 4, h} + 2.0 v^C_{8 \rightarrow 10, h} + v^C_{8 \rightarrow 10, l} + 3.0 v^C_{9 \rightarrow 10, h} + 2.0 v^C_{9 \rightarrow 10, l} + v^C_{7 \rightarrow 10, h} + v^C_{11 \rightarrow T, h} + 2.0 v^C_{12 \rightarrow T, h} + v^C_{12 \rightarrow T, l}>$\\
Subject To$\\
    A: cont-at-0 & $-1.0 v^A_{0 \rightarrow 1, h} -1.0 v^A_{0 \rightarrow 2, l} = -1.0$\\
    A: bin-link-1 & $\lambda_{x1} -1.0 v^A_{0 \rightarrow 1, h} = 0.0$\\
    A: cont-at-1 & $v^A_{0 \rightarrow 1, h} -1.0 v^A_{1 \rightarrow 3, h} -1.0 v^A_{1 \rightarrow 5, l} = 0.0$\\
    A: cont-at-2 & $v^A_{0 \rightarrow 2, l} -1.0 v^A_{2 \rightarrow 5, h} -1.0 v^A_{2 \rightarrow 4, l} = 0.0$\\
    A: bin-link-2 & $\lambda_{z1-1} -1.0 v^A_{1 \rightarrow 3, h} -1.0 v^A_{2 \rightarrow 5, h} = 0.0$\\
    A: cont-at-3 & $v^A_{1 \rightarrow 3, h} -1.0 v^A_{3 \rightarrow 6, h} -1.0 v^A_{3 \rightarrow 8, l} = 0.0$\\
    A: cont-at-4 & $v^A_{2 \rightarrow 4, l} -1.0 v^A_{4 \rightarrow 8, h} -1.0 v^A_{4 \rightarrow 7, l} = 0.0$\\
    A: cont-at-5 & $v^A_{1 \rightarrow 5, l} + v^A_{2 \rightarrow 5, h} -1.0 v^A_{5 \rightarrow 8, h} -1.0 v^A_{5 \rightarrow 8, l} = 0.0$\\
    A: bin-link-3 & $\lambda_{z1-2} -1.0 v^A_{3 \rightarrow 6, h} -1.0 v^A_{4 \rightarrow 8, h} -1.0 v^A_{5 \rightarrow 8, h} = 0.0$\\
    A: cont-at-8 & $v^A_{3 \rightarrow 8, l} + v^A_{4 \rightarrow 8, h} + v^A_{5 \rightarrow 8, h} + v^A_{5 \rightarrow 8, l} -1.0 v^A_{8 \rightarrow 10, h} -1.0 v^A_{8 \rightarrow 10, l} = 0.0$\\
    A: cont-at-6 & $v^A_{3 \rightarrow 6, h} -1.0 v^A_{6 \rightarrow 9, h} -1.0 v^A_{6 \rightarrow 10, l} = 0.0$\\
    A: cont-at-7 & $v^A_{4 \rightarrow 7, l} -1.0 v^A_{7 \rightarrow 10, h} -1.0 v^A_{7 \rightarrow 9, l} = 0.0$\\
    A: bin-link-4 & $\lambda_{z1-3} -1.0 v^A_{8 \rightarrow 10, h} -1.0 v^A_{6 \rightarrow 9, h} -1.0 v^A_{7 \rightarrow 10, h} = 0.0$\\
    A: cont-at-9 & $v^A_{6 \rightarrow 9, h} + v^A_{7 \rightarrow 9, l} -1.0 v^A_{9 \rightarrow 11, h} -1.0 v^A_{9 \rightarrow 12, l} = 0.0$\\
    A: cont-at-10 & $v^A_{8 \rightarrow 10, h} + v^A_{8 \rightarrow 10, l} + v^A_{6 \rightarrow 10, l} + v^A_{7 \rightarrow 10, h} -1.0 v^A_{10 \rightarrow 13, h} -1.0 v^A_{10 \rightarrow 13, l} = 0.0$\\
    A: bin-link-5 & $\lambda_{x2} -1.0 v^A_{9 \rightarrow 11, h} -1.0 v^A_{10 \rightarrow 13, h} = 0.0$\\
    A: cont-at-11 & $v^A_{9 \rightarrow 11, h} -1.0 v^A_{11 \rightarrow 14, h} -1.0 v^A_{11 \rightarrow 16, l} = 0.0$\\
    A: cont-at-12 & $v^A_{9 \rightarrow 12, l} -1.0 v^A_{12 \rightarrow 16, h} -1.0 v^A_{12 \rightarrow 15, l} = 0.0$\\
    A: cont-at-13 & $v^A_{10 \rightarrow 13, h} + v^A_{10 \rightarrow 13, l} -1.0 v^A_{13 \rightarrow 16, h} -1.0 v^A_{13 \rightarrow 16, l} = 0.0$\\
    A: bin-link-6 & $\lambda_{z2-2} -1.0 v^A_{11 \rightarrow 14, h} -1.0 v^A_{12 \rightarrow 16, h} -1.0 v^A_{13 \rightarrow 16, h} = 0.0$\\
    A: cont-at-14 & $v^A_{11 \rightarrow 14, h} -1.0 v^A_{14 \rightarrow 17, h} -1.0 v^A_{14 \rightarrow 19, l} = 0.0$\\
    A: cont-at-16 & $v^A_{11 \rightarrow 16, l} + v^A_{12 \rightarrow 16, h} + v^A_{13 \rightarrow 16, h} + v^A_{13 \rightarrow 16, l} -1.0 v^A_{16 \rightarrow 19, h} -1.0 v^A_{16 \rightarrow 19, l} = 0.0$\\
    A: cont-at-15 & $v^A_{12 \rightarrow 15, l} -1.0 v^A_{15 \rightarrow 19, h} -1.0 v^A_{15 \rightarrow 18, l} = 0.0$\\
    A: bin-link-7 & $\lambda_{z2-3} -1.0 v^A_{14 \rightarrow 17, h} -1.0 v^A_{16 \rightarrow 19, h} -1.0 v^A_{15 \rightarrow 19, h} = 0.0$\\
    A: cont-at-17 & $v^A_{14 \rightarrow 17, h} -1.0 v^A_{17 \rightarrow 20, h} -1.0 v^A_{17 \rightarrow 21, l} = 0.0$\\
    A: cont-at-18 & $v^A_{15 \rightarrow 18, l} -1.0 v^A_{18 \rightarrow 21, h} -1.0 v^A_{18 \rightarrow 20, l} = 0.0$\\
    A: cont-at-19 & $v^A_{14 \rightarrow 19, l} + v^A_{16 \rightarrow 19, h} + v^A_{16 \rightarrow 19, l} + v^A_{15 \rightarrow 19, h} -1.0 v^A_{19 \rightarrow 21, h} -1.0 v^A_{19 \rightarrow 21, l} = 0.0$\\
    A: bin-link-8 & $\lambda_{z2-4} -1.0 v^A_{17 \rightarrow 20, h} -1.0 v^A_{18 \rightarrow 21, h} -1.0 v^A_{19 \rightarrow 21, h} = 0.0$\\
    A: cont-at-20 & $v^A_{17 \rightarrow 20, h} + v^A_{18 \rightarrow 20, l} -1.0 v^A_{20 \rightarrow 22, h} -1.0 v^A_{20 \rightarrow 23, l} = 0.0$\\
    A: cont-at-21 & $v^A_{17 \rightarrow 21, l} + v^A_{18 \rightarrow 21, h} + v^A_{19 \rightarrow 21, h} + v^A_{19 \rightarrow 21, l} -1.0 v^A_{21 \rightarrow 24, h} -1.0 v^A_{21 \rightarrow 24, l} = 0.0$\\
    A: bin-link-9 & $\lambda_{x3} -1.0 v^A_{20 \rightarrow 22, h} -1.0 v^A_{21 \rightarrow 24, h} = 0.0$\\
    A: cont-at-24 & $v^A_{21 \rightarrow 24, h} + v^A_{21 \rightarrow 24, l} -1.0 v^A_{24 \rightarrow 27, h} -1.0 v^A_{24 \rightarrow 27, l} = 0.0$\\
    A: cont-at-23 & $v^A_{20 \rightarrow 23, l} -1.0 v^A_{23 \rightarrow 27, h} -1.0 v^A_{23 \rightarrow 26, l} = 0.0$\\
    A: cont-at-22 & $v^A_{20 \rightarrow 22, h} -1.0 v^A_{22 \rightarrow 25, h} -1.0 v^A_{22 \rightarrow 27, l} = 0.0$\\
    A: bin-link-10 & $\lambda_{z3-3} -1.0 v^A_{24 \rightarrow 27, h} -1.0 v^A_{23 \rightarrow 27, h} -1.0 v^A_{22 \rightarrow 25, h} = 0.0$\\
    A: cont-at-25 & $v^A_{22 \rightarrow 25, h} -1.0 v^A_{25 \rightarrow T, h} -1.0 v^A_{25 \rightarrow F, l} = 0.0$\\
    A: cont-at-26 & $v^A_{23 \rightarrow 26, l} -1.0 v^A_{26 \rightarrow F, h} -1.0 v^A_{26 \rightarrow T, l} = 0.0$\\
    A: cont-at-27 & $v^A_{24 \rightarrow 27, h} + v^A_{24 \rightarrow 27, l} + v^A_{23 \rightarrow 27, h} + v^A_{22 \rightarrow 27, l} -1.0 v^A_{27 \rightarrow F, h} -1.0 v^A_{27 \rightarrow F, l} = 0.0$\\
    A: bin-link-11 & $\lambda_{z3-4} -1.0 v^A_{25 \rightarrow T, h} -1.0 v^A_{26 \rightarrow F, h} -1.0 v^A_{27 \rightarrow F, h} = 0.0$\\
    A: cont-at-T & $v^A_{25 \rightarrow T, h} + v^A_{26 \rightarrow T, l} = 1.0$\\
    A: cont-at-F & $v^A_{25 \rightarrow F, l} + v^A_{26 \rightarrow F, h} + v^A_{27 \rightarrow F, h} + v^A_{27 \rightarrow F, l} = 0.0$\\
    C: cont-at-0 & $-1.0 v^C_{0 \rightarrow 1, h} -1.0 v^C_{0 \rightarrow 1, l} = -1.0$\\
    C: bin-link-1 & $\lambda_{z1-1} -1.0 v^C_{0 \rightarrow 1, h} = 0.0$\\
    C: cont-at-1 & $v^C_{0 \rightarrow 1, h} + v^C_{0 \rightarrow 1, l} -1.0 v^C_{1 \rightarrow 3, h} -1.0 v^C_{1 \rightarrow 2, l} = 0.0$\\
    C: bin-link-2 & $\lambda_{z1-2} -1.0 v^C_{1 \rightarrow 3, h} = 0.0$\\
    C: cont-at-3 & $v^C_{1 \rightarrow 3, h} -1.0 v^C_{3 \rightarrow 4, h} -1.0 v^C_{3 \rightarrow 4, l} = 0.0$\\
    C: cont-at-2 & $v^C_{1 \rightarrow 2, l} -1.0 v^C_{2 \rightarrow 4, h} -1.0 v^C_{2 \rightarrow 4, l} = 0.0$\\
    C: bin-link-3 & $\lambda_{z2-2} -1.0 v^C_{3 \rightarrow 4, h} -1.0 v^C_{2 \rightarrow 4, h} = 0.0$\\
    C: cont-at-4 & $v^C_{3 \rightarrow 4, h} + v^C_{3 \rightarrow 4, l} + v^C_{2 \rightarrow 4, h} + v^C_{2 \rightarrow 4, l} -1.0 v^C_{4 \rightarrow 6, h} -1.0 v^C_{4 \rightarrow 5, l} = 0.0$\\
    C: bin-link-4 & $\lambda_{z1-3} -1.0 v^C_{4 \rightarrow 6, h} = 0.0$\\
    C: cont-at-6 & $v^C_{4 \rightarrow 6, h} -1.0 v^C_{6 \rightarrow 9, h} -1.0 v^C_{6 \rightarrow 8, l} = 0.0$\\
    C: cont-at-5 & $v^C_{4 \rightarrow 5, l} -1.0 v^C_{5 \rightarrow 8, h} -1.0 v^C_{5 \rightarrow 7, l} = 0.0$\\
    C: bin-link-5 & $\lambda_{z2-3} -1.0 v^C_{6 \rightarrow 9, h} -1.0 v^C_{5 \rightarrow 8, h} = 0.0$\\
    C: cont-at-8 & $v^C_{6 \rightarrow 8, l} + v^C_{5 \rightarrow 8, h} -1.0 v^C_{8 \rightarrow 10, h} -1.0 v^C_{8 \rightarrow 10, l} = 0.0$\\
    C: cont-at-9 & $v^C_{6 \rightarrow 9, h} -1.0 v^C_{9 \rightarrow 10, h} -1.0 v^C_{9 \rightarrow 10, l} = 0.0$\\
    C: cont-at-7 & $v^C_{5 \rightarrow 7, l} -1.0 v^C_{7 \rightarrow 10, h} -1.0 v^C_{7 \rightarrow 10, l} = 0.0$\\
    C: bin-link-6 & $\lambda_{z3-3} -1.0 v^C_{8 \rightarrow 10, h} -1.0 v^C_{9 \rightarrow 10, h} -1.0 v^C_{7 \rightarrow 10, h} = 0.0$\\
    C: cont-at-10 & $v^C_{8 \rightarrow 10, h} + v^C_{8 \rightarrow 10, l} + v^C_{9 \rightarrow 10, h} + v^C_{9 \rightarrow 10, l} + v^C_{7 \rightarrow 10, h} + v^C_{7 \rightarrow 10, l} -1.0 v^C_{10 \rightarrow 12, h} -1.0 v^C_{10 \rightarrow 11, l} = 0.0$\\
    C: bin-link-7 & $\lambda_{z2-4} -1.0 v^C_{10 \rightarrow 12, h} = 0.0$\\
    C: cont-at-11 & $v^C_{10 \rightarrow 11, l} -1.0 v^C_{11 \rightarrow T, h} -1.0 v^C_{11 \rightarrow T, l} = 0.0$\\
    C: cont-at-12 & $v^C_{10 \rightarrow 12, h} -1.0 v^C_{12 \rightarrow T, h} -1.0 v^C_{12 \rightarrow T, l} = 0.0$\\
    C: bin-link-8 & $\lambda_{z3-4} -1.0 v^C_{11 \rightarrow T, h} -1.0 v^C_{12 \rightarrow T, h} = 0.0$\\
    C: cont-at-T & $v^C_{11 \rightarrow T, h} + v^C_{11 \rightarrow T, l} + v^C_{12 \rightarrow T, h} + v^C_{12 \rightarrow T, l} = 1.0$\\
    C: cont-at-F & $0.0 = 0.0$\\
Binaries$\\
   ['\lambda_{x1}', '\lambda_{z1-1}', '\lambda_{z1-2}', '\lambda_{z1-3}', '\lambda_{x2}', '\lambda_{z2-2}', '\lambda_{z2-3}', '\lambda_{z2-4}', '\lambda_{x3}', '\lambda_{z3-3}', '\lambda_{z3-4}']$\\
#+end_example

* Objective and general notes.
#+begin_export latex
\begin{flalign*}
\textrm{Minimize:}\quad\quad     & 0.1 v^A_{0 \rightarrow 1, h} + 0.2 v^A_{9 \rightarrow 11, h} + 0.2 v^A_{10 \rightarrow 13, h} + 0.3 v^A_{20 \rightarrow 22, h} + 0.3 v^A_{21 \rightarrow 24, h} + \\
& v^C_{0 \rightarrow 1, h} + 2.0 v^C_{3 \rightarrow 4, h} + v^C_{3 \rightarrow 4, l} + v^C_{2 \rightarrow 4, h} + \\
& 2.0 v^C_{8 \rightarrow 10, h} + v^C_{8 \rightarrow 10, l} + 3.0 v^C_{9 \rightarrow 10, h} + 2.0 v^C_{9 \rightarrow 10, l} + v^C_{7 \rightarrow 10, h} + \\
& v^C_{11 \rightarrow T, h} + 2.0 v^C_{12 \rightarrow T, h} + v^C_{12 \rightarrow T, l}
\end{flalign*}
#+end_export
Here, for example, variable $v^A_{0\rightarrow 1,h}$ corresponds to the flow
from node \textcircled{0} to node \textcircled{1} of diagram $A$ (availability),
along the "hi" ("yes") arc.\\


*Legend.*
- From each diagram, two types of constraints are generated:
  + /cont-at-\textcircled{.}/ are flow continuity constraints at a given node.
  + /bin-link-<k>/ are binary linking constraints (needed to link two BDDs -- i.e.,
    tangle network flow problems), one per layer, indexed with $k$.
- $A$ denotes "Availability" diagram, $C$ denotes "Covering"
  diagram.
  
All node numbers correspond to the diagrams and have nothing to do with
customer and facility indices.

- Arc flow variables (continuous) $v$.
- Linking variables (binary): $[\lambda_{x1}, \lambda_{z1-1}, \lambda_{z1-2}, \lambda_{z1-3}, \lambda_{x2}, \lambda_{z2-2}, \lambda_{z2-3}, \lambda_{z2-4}, \lambda_{x3}, \lambda_{z3-3}, \lambda_{z3-4}]$.

  *Note:* All this is generated automatically. That is,
  - *Input:* "customer proximity" lists $S_j$ (customers vs. facility
    proximity), (no covering costs $c_{ij}$ anymore), switch-on costs $f_i$, overlap penalty $g_j(n_j)$.
  - *Output:* (weighted) BDDs: covering and availability. CPP MiP (what is
    below: already a snapshot of a Gurobi model object: output of
    =gurobipy.Model.display()= converted to \LaTeX{} with a semi-automatic
    procedure.

* Constraints from Availability diagram.

   #+begin_export latex
\begin{tabular}{l l}
\textbf{Type} & \textbf{Constraint}\\\hline\\
    A: cont-at-0 & $-1.0 v^A_{0 \rightarrow 1, h} -1.0 v^A_{0 \rightarrow 2, l} = -1.0$\\
    A: bin-link-1 & $\lambda_{x1} -1.0 v^A_{0 \rightarrow 1, h} = 0.0$\\
    A: cont-at-1 & $v^A_{0 \rightarrow 1, h} -1.0 v^A_{1 \rightarrow 3, h} -1.0 v^A_{1 \rightarrow 5, l} = 0.0$\\
    A: cont-at-2 & $v^A_{0 \rightarrow 2, l} -1.0 v^A_{2 \rightarrow 5, h} -1.0 v^A_{2 \rightarrow 4, l} = 0.0$\\
    A: bin-link-2 & $\lambda_{z1-1} -1.0 v^A_{1 \rightarrow 3, h} -1.0 v^A_{2 \rightarrow 5, h} = 0.0$\\
    A: cont-at-3 & $v^A_{1 \rightarrow 3, h} -1.0 v^A_{3 \rightarrow 6, h} -1.0 v^A_{3 \rightarrow 8, l} = 0.0$\\
    A: cont-at-4 & $v^A_{2 \rightarrow 4, l} -1.0 v^A_{4 \rightarrow 8, h} -1.0 v^A_{4 \rightarrow 7, l} = 0.0$\\
    A: cont-at-5 & $v^A_{1 \rightarrow 5, l} + v^A_{2 \rightarrow 5, h} -1.0 v^A_{5 \rightarrow 8, h} -1.0 v^A_{5 \rightarrow 8, l} = 0.0$\\
    A: bin-link-3 & $\lambda_{z1-2} -1.0 v^A_{3 \rightarrow 6, h} -1.0 v^A_{4 \rightarrow 8, h} -1.0 v^A_{5 \rightarrow 8, h} = 0.0$\\
    A: cont-at-8 & $v^A_{3 \rightarrow 8, l} + v^A_{4 \rightarrow 8, h} + v^A_{5 \rightarrow 8, h} + v^A_{5 \rightarrow 8, l} -1.0 v^A_{8 \rightarrow 10, h} -1.0 v^A_{8 \rightarrow 10, l} = 0.0$\\
    A: cont-at-6 & $v^A_{3 \rightarrow 6, h} -1.0 v^A_{6 \rightarrow 9, h} -1.0 v^A_{6 \rightarrow 10, l} = 0.0$\\
    A: cont-at-7 & $v^A_{4 \rightarrow 7, l} -1.0 v^A_{7 \rightarrow 10, h} -1.0 v^A_{7 \rightarrow 9, l} = 0.0$\\
    A: bin-link-4 & $\lambda_{z1-3} -1.0 v^A_{8 \rightarrow 10, h} -1.0 v^A_{6 \rightarrow 9, h} -1.0 v^A_{7 \rightarrow 10, h} = 0.0$\\
    A: cont-at-9 & $v^A_{6 \rightarrow 9, h} + v^A_{7 \rightarrow 9, l} -1.0 v^A_{9 \rightarrow 11, h} -1.0 v^A_{9 \rightarrow 12, l} = 0.0$\\
    A: cont-at-10 & $v^A_{8 \rightarrow 10, h} + v^A_{8 \rightarrow 10, l} + v^A_{6 \rightarrow 10, l} + v^A_{7 \rightarrow 10, h} -1.0 v^A_{10 \rightarrow 13, h} -1.0 v^A_{10 \rightarrow 13, l} = 0.0$\\
    A: bin-link-5 & $\lambda_{x2} -1.0 v^A_{9 \rightarrow 11, h} -1.0 v^A_{10 \rightarrow 13, h} = 0.0$\\
    A: cont-at-11 & $v^A_{9 \rightarrow 11, h} -1.0 v^A_{11 \rightarrow 14, h} -1.0 v^A_{11 \rightarrow 16, l} = 0.0$\\
    A: cont-at-12 & $v^A_{9 \rightarrow 12, l} -1.0 v^A_{12 \rightarrow 16, h} -1.0 v^A_{12 \rightarrow 15, l} = 0.0$\\
    A: cont-at-13 & $v^A_{10 \rightarrow 13, h} + v^A_{10 \rightarrow 13, l} -1.0 v^A_{13 \rightarrow 16, h} -1.0 v^A_{13 \rightarrow 16, l} = 0.0$\\
    A: bin-link-6 & $\lambda_{z2-2} -1.0 v^A_{11 \rightarrow 14, h} -1.0 v^A_{12 \rightarrow 16, h} -1.0 v^A_{13 \rightarrow 16, h} = 0.0$\\
    A: cont-at-14 & $v^A_{11 \rightarrow 14, h} -1.0 v^A_{14 \rightarrow 17, h} -1.0 v^A_{14 \rightarrow 19, l} = 0.0$\\
    A: cont-at-16 & $v^A_{11 \rightarrow 16, l} + v^A_{12 \rightarrow 16, h} + v^A_{13 \rightarrow 16, h} + v^A_{13 \rightarrow 16, l} -1.0 v^A_{16 \rightarrow 19, h} -1.0 v^A_{16 \rightarrow 19, l} = 0.0$\\
    A: cont-at-15 & $v^A_{12 \rightarrow 15, l} -1.0 v^A_{15 \rightarrow 19, h} -1.0 v^A_{15 \rightarrow 18, l} = 0.0$\\
    A: bin-link-7 & $\lambda_{z2-3} -1.0 v^A_{14 \rightarrow 17, h} -1.0 v^A_{16 \rightarrow 19, h} -1.0 v^A_{15 \rightarrow 19, h} = 0.0$\\
    A: cont-at-17 & $v^A_{14 \rightarrow 17, h} -1.0 v^A_{17 \rightarrow 20, h} -1.0 v^A_{17 \rightarrow 21, l} = 0.0$\\
    A: cont-at-18 & $v^A_{15 \rightarrow 18, l} -1.0 v^A_{18 \rightarrow 21, h} -1.0 v^A_{18 \rightarrow 20, l} = 0.0$\\
    A: cont-at-19 & $v^A_{14 \rightarrow 19, l} + v^A_{16 \rightarrow 19, h} + v^A_{16 \rightarrow 19, l} + v^A_{15 \rightarrow 19, h} -1.0 v^A_{19 \rightarrow 21, h} -1.0 v^A_{19 \rightarrow 21, l} = 0.0$\\
    A: bin-link-8 & $\lambda_{z2-4} -1.0 v^A_{17 \rightarrow 20, h} -1.0 v^A_{18 \rightarrow 21, h} -1.0 v^A_{19 \rightarrow 21, h} = 0.0$\\
    A: cont-at-20 & $v^A_{17 \rightarrow 20, h} + v^A_{18 \rightarrow 20, l} -1.0 v^A_{20 \rightarrow 22, h} -1.0 v^A_{20 \rightarrow 23, l} = 0.0$\\
    A: cont-at-21 & $v^A_{17 \rightarrow 21, l} + v^A_{18 \rightarrow 21, h} + v^A_{19 \rightarrow 21, h} + v^A_{19 \rightarrow 21, l} -1.0 v^A_{21 \rightarrow 24, h} -1.0 v^A_{21 \rightarrow 24, l} = 0.0$\\
    A: bin-link-9 & $\lambda_{x3} -1.0 v^A_{20 \rightarrow 22, h} -1.0 v^A_{21 \rightarrow 24, h} = 0.0$\\
    A: cont-at-24 & $v^A_{21 \rightarrow 24, h} + v^A_{21 \rightarrow 24, l} -1.0 v^A_{24 \rightarrow 27, h} -1.0 v^A_{24 \rightarrow 27, l} = 0.0$\\
    A: cont-at-23 & $v^A_{20 \rightarrow 23, l} -1.0 v^A_{23 \rightarrow 27, h} -1.0 v^A_{23 \rightarrow 26, l} = 0.0$\\
    A: cont-at-22 & $v^A_{20 \rightarrow 22, h} -1.0 v^A_{22 \rightarrow 25, h} -1.0 v^A_{22 \rightarrow 27, l} = 0.0$\\
    A: bin-link-10 & $\lambda_{z3-3} -1.0 v^A_{24 \rightarrow 27, h} -1.0 v^A_{23 \rightarrow 27, h} -1.0 v^A_{22 \rightarrow 25, h} = 0.0$\\
    A: cont-at-25 & $v^A_{22 \rightarrow 25, h} -1.0 v^A_{25 \rightarrow T, h} -1.0 v^A_{25 \rightarrow F, l} = 0.0$\\
    A: cont-at-26 & $v^A_{23 \rightarrow 26, l} -1.0 v^A_{26 \rightarrow F, h} -1.0 v^A_{26 \rightarrow T, l} = 0.0$\\
    A: cont-at-27 & $v^A_{24 \rightarrow 27, h} + v^A_{24 \rightarrow 27, l} + v^A_{23 \rightarrow 27, h} + v^A_{22 \rightarrow 27, l} -1.0 v^A_{27 \rightarrow F, h} -1.0 v^A_{27 \rightarrow F, l} = 0.0$\\
    A: bin-link-11 & $\lambda_{z3-4} -1.0 v^A_{25 \rightarrow T, h} -1.0 v^A_{26 \rightarrow F, h} -1.0 v^A_{27 \rightarrow F, h} = 0.0$\\
    A: cont-at-T & $v^A_{25 \rightarrow T, h} + v^A_{26 \rightarrow T, l} = 1.0$\\
    A: cont-at-F & $v^A_{25 \rightarrow F, l} + v^A_{26 \rightarrow F, h} + v^A_{27 \rightarrow F, h} + v^A_{27 \rightarrow F, l} = 0.0$
\end{tabular}
#+end_export

* Constraints from Covering diagram.
#+begin_export latex
\begin{tabular}{l l}
\textbf{Type} & \textbf{Constraint}\\\hline\\
    C: cont-at-0 & $-1.0 v^C_{0 \rightarrow 1, h} -1.0 v^C_{0 \rightarrow 1, l} = -1.0$\\
    C: bin-link-1 & $\lambda_{z1-1} -1.0 v^C_{0 \rightarrow 1, h} = 0.0$\\
    C: cont-at-1 & $v^C_{0 \rightarrow 1, h} + v^C_{0 \rightarrow 1, l} -1.0 v^C_{1 \rightarrow 3, h} -1.0 v^C_{1 \rightarrow 2, l} = 0.0$\\
    C: bin-link-2 & $\lambda_{z1-2} -1.0 v^C_{1 \rightarrow 3, h} = 0.0$\\
    C: cont-at-3 & $v^C_{1 \rightarrow 3, h} -1.0 v^C_{3 \rightarrow 4, h} -1.0 v^C_{3 \rightarrow 4, l} = 0.0$\\
    C: cont-at-2 & $v^C_{1 \rightarrow 2, l} -1.0 v^C_{2 \rightarrow 4, h} -1.0 v^C_{2 \rightarrow 4, l} = 0.0$\\
    C: bin-link-3 & $\lambda_{z2-2} -1.0 v^C_{3 \rightarrow 4, h} -1.0 v^C_{2 \rightarrow 4, h} = 0.0$\\
    C: cont-at-4 & $v^C_{3 \rightarrow 4, h} + v^C_{3 \rightarrow 4, l} + v^C_{2 \rightarrow 4, h} + v^C_{2 \rightarrow 4, l} -1.0 v^C_{4 \rightarrow 6, h} -1.0 v^C_{4 \rightarrow 5, l} = 0.0$\\
    C: bin-link-4 & $\lambda_{z1-3} -1.0 v^C_{4 \rightarrow 6, h} = 0.0$\\
    C: cont-at-6 & $v^C_{4 \rightarrow 6, h} -1.0 v^C_{6 \rightarrow 9, h} -1.0 v^C_{6 \rightarrow 8, l} = 0.0$\\
    C: cont-at-5 & $v^C_{4 \rightarrow 5, l} -1.0 v^C_{5 \rightarrow 8, h} -1.0 v^C_{5 \rightarrow 7, l} = 0.0$\\
    C: bin-link-5 & $\lambda_{z2-3} -1.0 v^C_{6 \rightarrow 9, h} -1.0 v^C_{5 \rightarrow 8, h} = 0.0$\\
    C: cont-at-8 & $v^C_{6 \rightarrow 8, l} + v^C_{5 \rightarrow 8, h} -1.0 v^C_{8 \rightarrow 10, h} -1.0 v^C_{8 \rightarrow 10, l} = 0.0$\\
    C: cont-at-9 & $v^C_{6 \rightarrow 9, h} -1.0 v^C_{9 \rightarrow 10, h} -1.0 v^C_{9 \rightarrow 10, l} = 0.0$\\
    C: cont-at-7 & $v^C_{5 \rightarrow 7, l} -1.0 v^C_{7 \rightarrow 10, h} -1.0 v^C_{7 \rightarrow 10, l} = 0.0$\\
    C: bin-link-6 & $\lambda_{z3-3} -1.0 v^C_{8 \rightarrow 10, h} -1.0 v^C_{9 \rightarrow 10, h} -1.0 v^C_{7 \rightarrow 10, h} = 0.0$\\
    C: cont-at-10 & $v^C_{8 \rightarrow 10, h} + v^C_{8 \rightarrow 10, l} + v^C_{9 \rightarrow 10, h} + v^C_{9 \rightarrow 10, l} + v^C_{7 \rightarrow 10, h} + v^C_{7 \rightarrow 10, l} -1.0 v^C_{10 \rightarrow 12, h} -1.0 v^C_{10 \rightarrow 11, l} = 0.0$\\
    C: bin-link-7 & $\lambda_{z2-4} -1.0 v^C_{10 \rightarrow 12, h} = 0.0$\\
    C: cont-at-11 & $v^C_{10 \rightarrow 11, l} -1.0 v^C_{11 \rightarrow T, h} -1.0 v^C_{11 \rightarrow T, l} = 0.0$\\
    C: cont-at-12 & $v^C_{10 \rightarrow 12, h} -1.0 v^C_{12 \rightarrow T, h} -1.0 v^C_{12 \rightarrow T, l} = 0.0$\\
    C: bin-link-8 & $\lambda_{z3-4} -1.0 v^C_{11 \rightarrow T, h} -1.0 v^C_{12 \rightarrow T, h} = 0.0$\\
    C: cont-at-T & $v^C_{11 \rightarrow T, h} + v^C_{11 \rightarrow T, l} + v^C_{12 \rightarrow T, h} + v^C_{12 \rightarrow T, l} = 1.0$\\
    C: cont-at-F & $0.0 = 0.0$
\end{tabular}
#+end_export

