#PBS -N jUFLP
#PBS -l select=1:ncpus=1:mem=15gb:interconnect=any,walltime=06:00:00
#PBS -j oe
#PBS -M abochka@g.clemson.edu
#PBS -m abe

cd /home/abochka/BDD/align-BDD
source .venv/bin/activate
module add gurobi

# run-command
tgs -m "Experiment started: rnd w/consecutive linking, n=11, M=7, L=0.35."
fname="run_logs/2022-06-23_jUFLP_vs_MIPs_consec.out"
python -m experiments.jUFLP_specins | tee $fname
tgs -m "Experiment done."
tgs -f $fname.csv
