#PBS -N jUFL_hist
#PBS -l select=1:ncpus=32:mem=32gb:interconnect=any,walltime=10:00:00
#PBS -j oe
#PBS -M abochka@clemson.edu
#PBS -m abe

module add anaconda3/5.1.0-gcc/8.3.1
source activate ab-local
module add gnu-parallel

cd /home/abochka/BDD/align-BDD

tgs -m "starting the run: jUFL run"
# run-command
./get_jUFL_hist.sh 32
tgs -m "Experiment done."
tgs -f run_logs/jUFL/logfile.csv
tgs -s happycat

# deactivate the env
source deactivate ab-local
