#PBS -N SZD
#PBS -l select=1:ncpus=1:mem=8gb,walltime=03:00:00
#PBS -j oe
#PBS -M abochka@clemson.edu
#PBS -m abe

# boilerplate things
STARTMSG="Running a quick scaling test"
ENDMSG="done."

module add anaconda3/5.1.0-gcc/8.3.1
source activate ab-local

cd /home/abochka/BDD/align-BDD

echo $STARTMSG | tgs -m -
./get_sizes.sh > run_logs/dia_sizes.csv
echo $ENDMSG | tgs -m -
tgs -f run_logs/dia_sizes.csv
tgs -s happycat
# deactivate the env
source deactivate ab-local

