#PBS -N Figs
#PBS -l select=1:ncpus=1:mem=1gb,walltime=00:10:00
#PBS -j oe
#PBS -o run_logs/sending.log

# boilerplate things

tg=/home/abochka/bin/tgsend.sh
tgi=/home/abochka/bin/tgsend_img.sh
tgs=/home/abochka/bin/tgsend_st.sh

cd /home/abochka/BDD/align-BDD

cd figures
ls | $tg > /dev/null
for file in $(ls); do
    convert $file $file.png
    $tgi $file.png
    rm $file.png
done
mkdir -p ./png
mv ./*.png png/
cd ..

echo "done sending images" | $tg > /dev/null
