install.packages(c(
    "dplyr",
    "ggplot2",
    "ggridges",
    "gridExtra",
    "latex2exp",
    "optparse",
    "reshape",
    "stringr",
    "tidyr",
    "xtable"),
    repos="http://cran.us.r-project.org")
